// <auto-generated />
using System;
using FirstGoalBets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchInfoService.Migrations
{
    [DbContext(typeof(FirstGoalBetsDBContext))]
    [Migration("20221113195600_UrlMatch")]
    partial class UrlMatch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MatchInfoService.Models.GoalsViewModel", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstGoal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalGoals")
                        .HasColumnType("int");

                    b.HasKey("GameID");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("MatchInfoService.Models.MatchViewModel", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AwayPlayerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HomePlayerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalGoals")
                        .HasColumnType("int");

                    b.Property<string>("UrlMatch")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GameID");

                    b.ToTable("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
